### ISSUE TITLE
RemoveYou for collections

### ISSUE THREAD

**Issue by eicke123** [fujaba/SDMLib#17]
When calling removeYou on an object, it should be removed from all containing collections.

**Comment by azuendorf** [comment]
removeYou removes the object from all collections it knows about. This means, if the object has a link to some partner and the partner has a reverse link, this reverse link is removed, too. 

If you make a collection on your own and add the object to it, the object does not know that it is 
contained in this collection and thus it can not remove itself from it. 

Overall, use bidrectional links generated by SDMLib and removeYou works as desired.
