### ISSUE TITLE
Create objects of abstract classes

### ISSUE THREAD

**Issue by marcusschmidt** [fujaba/SDMLib#3]
SDMLib currently creates objects for abstract classes which associetes to themselfs.

Try this for example:

package sdmlib;

import org.junit.Test;
import org.sdmlib.models.classes.Card;
import org.sdmlib.models.classes.ClassModel;
import org.sdmlib.models.classes.Clazz;
import org.sdmlib.models.classes.DataType;
import org.sdmlib.models.classes.Parameter;

public class ModelGenerator {

```
@Test
public void generateModel() {
    ClassModel cm = new ClassModel("de.uniks.se.dpss15.cor");

    Clazz bPlayer = cm
            .createClazz("BombermanPlayer")
            .withAttribute("xPosition", DataType.INT)
            .withAttribute("yPosition", DataType.INT)
            .withAttribute("numberOfBombs", DataType.INT)
            .withAttribute("lastKey", DataType.CHAR)
            .withMethod("keyPress", DataType.VOID,
                    new Parameter("key", DataType.STRING));

    Clazz bStrategy = cm.createClazz("BombermanStrategy")
            .withAbztract(true).withMethod("handleMove", DataType.VOID);

    bStrategy.createKidClazz("MoveUp");
    bStrategy.createKidClazz("MoveDown");
    bStrategy.createKidClazz("MoveLeft");
    bStrategy.createKidClazz("MoveRight");
    bStrategy.createKidClazz("Blast");
    bStrategy.createKidClazz("Stay");

    bStrategy.withUniDirectionalAssoc(bStrategy, "successor", Card.ONE);
    // bStrategy.withAssoc(bStrategy, "suc", Card.ONE, "pre", Card.ONE);

    cm.generate();
    cm.dumpHTML("classdiag");
}
```

}

This will create:
public BombermanStrategy createSuccessor()
   {
      BombermanStrategy value = new BombermanStrategy();
      withSuccessor(value);
      return value;
   } 

in BombermanStragy.java although BombermanStrategy is an abstract class

--Marcus

**Comment by azuendorf** [comment]
I have added your code to our test suite. I hope this is OK. 
Bug is fixed by las commit. 
Thanks for the hint.
